# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Kramp.DotNet.Models.CDM

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Pack
      run: dotnet pack --no-build --configuration Debug --output .
    - name: Add GitHub Source
      run: dotnet nuget add source --username richard-vandentoorn --password ${{secrets.nuget_api_key}} --name GitHub https://nuget.pkg.github.com/richard-vandentoorn/index.json --store-password-in-clear-text
    - name: Push
      run: dotnet nuget push *.nupkg --source GitHub --skip-duplicate
